### ISSUE TITLE
Responsividad en movil

### ISSUE THREAD

**Issue by Duarlo** [Daniel-GB0319/proyecto-ch39#40]
Saludos soy yo de nuevo. se que ya han de estar de todas mis revisiones asi.
![image](https://github.com/Daniel-GB0319/proyecto-ch39/assets/130912792/2cfd7756-2f42-4998-bc19-e0363d3542d6)

---
# Problemas de responsibidad de la navbar
 Considero que no es muy grave pero para tomar en cuenta cuando probemos la responsividad en movil como que se rompe la navbar.
Evidencias...
![image](https://github.com/Daniel-GB0319/proyecto-ch39/assets/130912792/229dfe58-7c9c-4e02-a6b0-8c70a752ca63)

Esto casi no sucede con pantallas grandes o intermedias pero si con moviles y tambien lo probe en mi telefono y se presenta este problema .Evidencias...

![image](https://github.com/Daniel-GB0319/proyecto-ch39/assets/130912792/b2d974d2-2cbb-4a9a-9f9c-240ae8cc3cc7)

Como ven el problema, lo deberiamos dejar asi.

---
![image](https://github.com/Daniel-GB0319/proyecto-ch39/assets/130912792/aa8daf77-a5d6-4299-a06f-c14a87409664)

**Comment by Daniel-GB0319** [comment]
Checando ese detalle, probablemente sea un problema con la navbar y el grid de nosotros.html. Si hacemos la prueba en index.html donde solo hay navbar y footer por ahora, pasa algo similar:

![image](https://github.com/Daniel-GB0319/proyecto-ch39/assets/83619266/8798b98a-7beb-4e9d-9340-f8987231acce)

Como se puede ver, unos elementos del navbar se quedan estáticos mientras lo demás se recorre, haciendo que se genere ese espacio sobrante a cierto tamaño de pantalla. Si tenemos la version movil o una vez que se activa el menu de hamburguesa, el espacio desaparece: 

![image](https://github.com/Daniel-GB0319/proyecto-ch39/assets/83619266/49e10d95-e91d-4e48-b535-1114f56691a4)

Para el caso de nosotros.html se muestra el siguiente resultado:

![image](https://github.com/Daniel-GB0319/proyecto-ch39/assets/83619266/1dc4d1cc-e866-4313-af31-4d94cf81cb2a)

pero cuando el navbar muestra el menú hamburguesa y ya se ajustaron nuevamente sus elementos, parte del grid de nosotros  sigue teniendo esos problemas de adaptarse al tamaño de la página:

![image](https://github.com/Daniel-GB0319/proyecto-ch39/assets/83619266/3db03172-4a07-43e7-8e1c-51acbb744b06)

![image](https://github.com/Daniel-GB0319/proyecto-ch39/assets/83619266/13f19750-e613-4bb5-9c67-3a18c87706a6)


Como conclusión, hay que checar la forma en que se adaptan los iconos en específico de la navbar que se quedan estáticos, además de checar como esta configurado el grid y sus elementos para dicha responsividad.

**Comment by Daniel-GB0319** [comment]
Yo me encargo de solucionar los problemas de la navbar, pero necesitamos que otras personas se encarguen del contenido y responsividad de nosotros.html

**Comment by Duarlo** [comment]
considerando los PR #47  y PR #53 se ha resuelto la responsibidad general de la pagina.
---
![image](https://github.com/Daniel-GB0319/proyecto-ch39/assets/130912792/5663855f-ee85-4ce5-ba95-90064e3a9779)
